Renaming improvements
substrate-developer-hub/substrate-developer-hub.github.io pull request #1080
Opened 2021-08-01 11:50 UTC by sacha-l

- Renaming the "Integrate" sidebar menu to "Toolchains"
- Move `try-runtime` article under "Toolchains"
- Rename article "Why are there no Hash collections in sp_std?"  to "Hash Collections"

2021-08-03 03:39 UTC, NukeManDan commented
My first thought on "toolchains" is the rust toolchain 😅  - not sure what the overall impression you want to send with the title of the section.

2021-08-03 11:54 UTC, sacha-l commented
> My first thought on "toolchains" is the rust toolchain  - not sure what the overall impression you want to send with the title of the section. I think "Integrations" might be a _bit_ misleading, but implies the thing I _think_ it should contain: `tooling to use with substrate nodes` It's not about developing a substrate runtime/node, but _integrating_ other applications with your node. 

This change is the result of [this PR](https://github.com/paritytechmarcomms/substrate-docs/pull/11/files). I can't remember where this discussion originally occurred but I had voiced that "Integrate" is misleading and we concluded that ["Toolchains"](https://en.wikipedia.org/wiki/Toolchain#:~:text=In%20software%2C%20a%20toolchain%20is,a%20set%20of%20related%20programs.) is more appropriate (I think it was you that suggested it too!). I seem to remember my original suggestion was "Integration and Tooling".

@jimmychu0807 , would love to hear your thoughts here so we can all align. 

> Also unclear why you think hashmaps should move from "Advanced" to this section with that framing of the section's theme.

The change I made here was only a title change for the hash-collections article. The path remains:
`docs/knowledgebase/advanced/no-hash-collections.md `

2021-08-03 14:41 UTC, NukeManDan approved these changes

2021-08-03 14:43 UTC, NukeManDan commented
Got ya. Well worst case here is that we get feedback from the builders that the title is confusing. And this may break external links (to things like subkey)

Have you done a serve of our other repos and the Polkadot wiki for this? We need to before this lands IMHO.

2021-08-06 13:25 UTC, sacha-l commented
> Got ya. Well worst case here is that we get feedback from the builders that the title is confusing. And this may break external links (to things like subkey)
> 
> Have you done a serve of our other repos and the Polkadot wiki for this? We need to before this lands IMHO.

I decided to keep the "Integrate" menu name for now. It's not worth the overhaul. We'll be migrating to our new devhub soon enough.

2021-08-06 14:49 UTC, NukeManDan requested changes

2021-08-06 14:49 UTC, NukeManDan commented on docs/index.md
> +  [Polkadot-JS](knowledgebase/toolchains/polkadot-js) family of libraries.
Should we keep the same path structure? To not break external links.

2021-08-09 18:05 UTC, NukeManDan approved these changes

2021-08-09 18:05 UTC, merged