Update configure-a-pallet.md
substrate-developer-hub/substrate-developer-hub.github.io pull request #663
Opened 2020-09-10 00:30 UTC by NukeManDan

add the location of referenced code

- [ ] Are the audience and objective of the document clear? E.g. a document for developers that should teach them about transaction fees.
- [ ] Is the writing:
  - [ ] Clear: No jargon.
  - [ ] Precise: No ambiguous meanings.
  - [ ] Concise: Free of superfluous detail.
- [ ] Does it follow our style guide?
- [ ] If this is a new page, does the PR include the appropriate infrastructure, e.g. adding the page to a sidebar?
- [ ] Build the page ($ cd website && yarn start). Does it render properly? E.g. no funny lists or formatting.
- [ ] Do links go to rustdocs or devhub articles rather than code?
- [ ] If this PR addresses an issue in the queue, have you referenced it in the description?

2020-09-10 09:19 UTC, wheresaddie approved these changes

2020-09-10 15:07 UTC, danforbes requested changes
Can you please fix the line lengths to be consistent? I think we are using 100-character line lengths in this repo.

2020-09-10 17:00 UTC, wheresaddie commented
you can run prettier and set it as an extension to run line length by default @NukeManDan if you are in vscode

2020-09-10 19:35 UTC, JoshOrndorff approved these changes
Thanks!

2020-09-10 19:35 UTC, JoshOrndorff commented on docs/tutorials/add-a-pallet/configure-a-pallet.md
> +
```suggestion
is included in the [Node Template](https://github.com/substrate-developer-hub/substrate-node-template),
you will see the following `Trait` configuration trait:

```

2020-09-10 20:13 UTC, danforbes approved these changes
Thanks, guys :pray:

2020-09-11 00:35 UTC, NukeManDan commented on docs/tutorials/add-a-pallet/configure-a-pallet.md
> +
thanks for the line ending help 🙏🏼

2020-09-11 00:37 UTC, NukeManDan commented
@JoshOrndorff you fixed the only 100+ line I think? We set now? 😁

2020-09-11 10:56 UTC, danforbes commented
Is CI not running because this is coming from a fork? :thinking:

2020-09-11 10:57 UTC, danforbes commented on docs/tutorials/add-a-pallet/configure-a-pallet.md
> +**`./pallets/template/src/lib.rs`**
```suggestion
**`pallets/template/src/lib.rs`**
```

2020-09-11 11:35 UTC, merged